2024-02-18 19:34:55,645 INFO    MainThread:3618465 [wandb_setup.py:_flush():69] setting env: {}
2024-02-18 19:34:55,645 INFO    MainThread:3618465 [wandb_setup.py:_flush():69] setting login settings: {}
2024-02-18 19:34:55,645 INFO    MainThread:3618465 [wandb_init.py:_log_setup():337] Logging user logs to /trinity/home/a.kolesov/NOTBarycenters/stylegan2/notebooks/wandb/run-20240218_193455-ohbem3sc/logs/debug.log
2024-02-18 19:34:55,646 INFO    MainThread:3618465 [wandb_init.py:_log_setup():338] Logging internal logs to /trinity/home/a.kolesov/NOTBarycenters/stylegan2/notebooks/wandb/run-20240218_193455-ohbem3sc/logs/debug-internal.log
2024-02-18 19:34:55,646 INFO    MainThread:3618465 [wandb_init.py:init():370] calling init triggers
2024-02-18 19:34:55,647 INFO    MainThread:3618465 [wandb_init.py:init():375] wandb.init called with sweep_config: {}
config: {'K': 3, 'EPSILON': 1.0, 'LAMBDAS': [0.25, 0.5, 0.25], 'CLASSES': [0, 1, 2], 'DATASET_PATH': '../../../data/ave_celeba_green_v2/', 'DATASET': 'ave_celeba', 'SPHERE_PROJECTION': False, 'CHI_PROJECTION': False, 'FLAG_LATENT': True, 'GENERATOR_PATH': '../../../stylegan2_ada_pytorch_before/training-runs/00011-aligned_celeba-stylegan2/network-snapshot-008800.pkl', 'LATENT_ENCODER_SIZE': 256, 'LATENT_SIZE': 512, 'ALAE': False, 'RESNET_D_ENCODER': True, 'BATCH_SIZE': 64, 'IMG_SIZE': 64, 'NC': 3, 'NUM_EPOCHS': 1, 'INNER_ITERATIONS': 10, 'HIDDEN_SIZE': [1024, 1024], 'LR_LATENT_MLP': 0.0001, 'LR_ENCODER': 0.0001, 'LR_POTENTIAL': 0.0001, 'BETAS': (0.2, 0.99), 'GPU_DEVICE': 0, 'DEVICE': 'cuda:0', 'NAME_EXP': 'KL_EPS_1.0_ALAE_False_ENC_True_EPS_1.0'}
2024-02-18 19:34:55,647 INFO    MainThread:3618465 [wandb_init.py:init():390] re-initializing run, found existing run on stack: 2g181g6p
2024-02-18 19:34:55,648 INFO    MainThread:3618465 [wandb_run.py:finish():1293] finishing run emfalafeli/FINAL_experiments_strong_barycenter/2g181g6p
2024-02-18 19:34:55,649 INFO    MainThread:3618465 [jupyter.py:save_history():339] not saving jupyter history
2024-02-18 19:34:55,649 INFO    MainThread:3618465 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2024-02-18 19:34:55,649 INFO    MainThread:3618465 [wandb_init.py:_jupyter_teardown():269] cleaning up jupyter logic
2024-02-18 19:34:55,649 INFO    MainThread:3618465 [wandb_run.py:_atexit_cleanup():1593] got exitcode: 0
2024-02-18 19:34:55,649 INFO    MainThread:3618465 [wandb_run.py:_restore():1565] restore
2024-02-18 19:34:56,510 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 703
  total_bytes: 703
}

2024-02-18 19:34:56,814 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 703
  total_bytes: 703
}

2024-02-18 19:34:56,916 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 703
  total_bytes: 6616
}

2024-02-18 19:34:57,018 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 703
  total_bytes: 6616
}

2024-02-18 19:34:57,119 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 703
  total_bytes: 6616
}

2024-02-18 19:34:57,220 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 6616
  total_bytes: 6616
}

2024-02-18 19:34:57,322 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 6616
  total_bytes: 6616
}

2024-02-18 19:34:57,423 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 6616
  total_bytes: 6616
}

2024-02-18 19:34:57,524 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 6616
  total_bytes: 6616
}

2024-02-18 19:34:57,625 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 6616
  total_bytes: 6616
}

2024-02-18 19:34:57,962 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 6616
  total_bytes: 6616
}

2024-02-18 19:34:58,063 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 6616
  total_bytes: 6616
}

2024-02-18 19:34:59,134 INFO    MainThread:3618465 [wandb_run.py:_show_files():1937] logging synced files
2024-02-18 19:34:59,138 INFO    MainThread:3618465 [wandb_init.py:init():419] starting backend
2024-02-18 19:34:59,138 INFO    MainThread:3618465 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-18 19:34:59,141 INFO    MainThread:3618465 [backend.py:ensure_launched():135] starting backend process...
2024-02-18 19:34:59,152 INFO    MainThread:3618465 [backend.py:ensure_launched():139] started backend process with pid: 3637038
2024-02-18 19:34:59,153 INFO    MainThread:3618465 [wandb_init.py:init():424] backend started and connected
2024-02-18 19:34:59,168 INFO    MainThread:3618465 [wandb_run.py:_label_probe_notebook():844] probe notebook
2024-02-18 19:34:59,168 INFO    MainThread:3618465 [wandb_run.py:_label_probe_notebook():851] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-18 19:34:59,168 INFO    MainThread:3618465 [wandb_init.py:init():472] updated telemetry
2024-02-18 19:34:59,172 INFO    MainThread:3618465 [wandb_init.py:init():491] communicating current version
2024-02-18 19:34:59,886 INFO    MainThread:3618465 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.16.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-02-18 19:34:59,887 INFO    MainThread:3618465 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2024-02-18 19:35:01,276 INFO    MainThread:3618465 [wandb_init.py:init():529] starting run threads in backend
2024-02-18 19:35:01,944 INFO    MainThread:3618465 [wandb_run.py:_console_start():1623] atexit reg
2024-02-18 19:35:01,945 INFO    MainThread:3618465 [wandb_run.py:_redirect():1497] redirect: SettingsConsole.WRAP
2024-02-18 19:35:01,945 INFO    MainThread:3618465 [wandb_run.py:_redirect():1534] Wrapping output streams.
2024-02-18 19:35:01,946 INFO    MainThread:3618465 [wandb_run.py:_redirect():1558] Redirects installed.
2024-02-18 19:35:01,947 INFO    MainThread:3618465 [wandb_init.py:init():554] run started, returning control to user process
2024-02-18 19:35:30,516 INFO    MainThread:3618465 [wandb_run.py:_atexit_cleanup():1593] got exitcode: 0
2024-02-18 19:35:30,517 INFO    MainThread:3618465 [wandb_run.py:_restore():1565] restore
2024-02-18 19:35:31,482 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 703
  total_bytes: 703
}

2024-02-18 19:35:31,751 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 703
  total_bytes: 703
}

2024-02-18 19:35:32,319 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 703
  total_bytes: 7742
}

2024-02-18 19:35:32,421 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 703
  total_bytes: 7742
}

2024-02-18 19:35:32,522 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 703
  total_bytes: 7742
}

2024-02-18 19:35:32,624 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 703
  total_bytes: 7742
}

2024-02-18 19:35:32,725 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7742
  total_bytes: 7742
}

2024-02-18 19:35:32,827 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7742
  total_bytes: 7742
}

2024-02-18 19:35:32,929 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7742
  total_bytes: 7742
}

2024-02-18 19:35:33,031 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7742
  total_bytes: 7742
}

2024-02-18 19:35:33,454 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7742
  total_bytes: 7742
}

2024-02-18 19:35:33,555 INFO    MainThread:3618465 [wandb_run.py:_wait_for_finish():1715] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7742
  total_bytes: 7742
}

2024-02-18 19:35:34,626 INFO    MainThread:3618465 [wandb_run.py:_show_files():1937] logging synced files
